cf.difficulty = [0.2, 0.4, 0.6, 0.8, 1]
cf.difficultyName = ["Amoeba", "Human", "Hero", "Superhero", "Godlike"]
cf.exercises = [
	{"group": "row", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Reverse Pushups", "grp": 1, "maximum": 80, "multiple": 5},
	{"group": "snatch", "bumper": false, "weight": .25, "not-reps": false, "maxweight": 55, "name": "Kettle Bell Snatch (per arm)", "grp": 1, "maximum": 50, "multiple": 5},
	{"group": "spress", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Handstand Pushups", "grp": 1, "maximum": 40, "multiple": 2},
	{"group": "pullup", "bumper": false, "weight": .5, "not-reps": false, "maxweight": 0, "name": "Towel pullups", "grp": 1, "maximum": 40, "multiple": 2},
	{"group": "backextension", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Back extension", "grp": 1, "maximum": 100, "multiple": 5},
	{"group": "cardio", "bumper": false, "weight": .5, "not-reps": true, "maxweight": 0, "name": "Jump Rope", "grp": 1, "maximum": 500, "multiple": 10},
	{"group": "swing", "bumper": false, "weight": .25, "not-reps": false, "maxweight": 55, "name": "2-Hand Kettle Bell Swings", "grp": 1, "maximum": 80, "multiple": 5},
	{"group": "jacks", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Jumping Jacks", "grp": 1, "maximum": 100, "multiple": 5},
	{"group": "pullup", "bumper": false, "weight": .5, "not-reps": false, "maxweight": 0, "name": "Chins", "grp": 1, "maximum": 60, "multiple": 5},
	{"group": "pullup", "bumper": false, "weight": .5, "not-reps": false, "maxweight": 0, "name": "Pullups", "grp": 1, "maximum": 60, "multiple": 5},
	{"group": "pressup", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Press-ups", "grp": 1, "maximum": 80, "multiple": 5},
	{"group": "pushpress", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 135, "name": "Thrusters", "grp": 1, "maximum": 60, "multiple": 5},
	{"group": "dip", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Dips", "grp": 1, "maximum": 60, "multiple": 5},
	{"group": "highpull", "bumper": false, "weight": .25, "not-reps": false, "maxweight": 55, "name": "Kettle Bell High Pull (per arm)", "grp": 1, "maximum": 40, "multiple": 5},
	{"group": "crunches", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Crunches", "grp": 1, "maximum": 100, "multiple": 5},
	{"group": "crunchthrow", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Medicine ball crunch/throw", "grp": 1, "maximum": 100, "multiple": 5},
	{"group": "hipflex", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Leg raises", "grp": 1, "maximum": 100, "multiple": 5},
	{"group": "clean", "bumper": false, "weight": .25, "not-reps": false, "maxweight": 55, "name": "Kettle Bell Cleans (per arm)", "grp": 1, "maximum": 50, "multiple": 5},
	{"group": "squat", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Squats", "grp": 1, "maximum": 100, "multiple": 5},
	{"group": "deadlift", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 225, "name": "Deadlift", "grp": 2, "maximum": 50, "multiple": 5},
	{"group": "deadlift", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 315, "name": "Sumo Deadlift", "grp": 2, "maximum": 50, "multiple": 5},
	{"group": "benchpress", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 185, "name": "Bench press", "grp": 2, "maximum": 80, "multiple": 5},
	{"group": "benchpress", "bumper": false, "weight": .5, "not-reps": false, "maxweight": 225, "name": "Heavy Bench press", "grp": 2, "maximum": 50, "multiple": 5},
	{"group": "spress", "bumper": false, "weight": .25, "not-reps": false, "maxweight": 55, "name": "2-arm Kettle Bell Military Press", "grp": 1, "maximum": 50, "multiple": 5},
	{"group": "squat", "bumper": false, "weight": .75, "not-reps": false, "maxweight": 225, "name": "Back squat", "grp": 2, "maximum": 60, "multiple": 5},
	{"group": "squat", "bumper": false, "weight": .75, "not-reps": false, "maxweight": 135, "name": "Back squat", "grp": 2, "maximum": 100, "multiple": 5},
	{"group": "spress", "bumper": false, "weight": .75, "not-reps": false, "maxweight": 185, "name": "Barbell push-press", "grp": 2, "maximum": 60, "multiple": 5},
	{"group": "spress", "bumper": false, "weight": .75, "not-reps": false, "maxweight": 135, "name": "Barbell press", "grp": 2, "maximum": 60, "multiple": 5},
	{"group": "shrug", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 225, "name": "Shrugs", "grp": 2, "maximum": 80, "multiple": 5},
	{"group": "jacks", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Burpees", "grp": 1, "maximum": 80, "multiple": 5},
	{"group": "pullup", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Muscleups", "grp": 1, "maximum": 60, "multiple": 2},
	{"group": "boxjump", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Box jump", "grp": 1, "maximum": 100, "multiple": 5},
	{"group": "cardio", "bumper": false, "weight": .5, "not-reps": true, "maxweight": 0, "name": "Rowing (meters)", "grp": 1, "maximum": 2400, "multiple": 400},
	{"group": "cardio", "bumper": false, "weight": .5, "not-reps": true, "maxweight": 0, "name": "Running (meters)", "grp": 1, "maximum": 1600, "multiple": 400},
	{"group": "row", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 135, "name": "Barbell Row", "grp": 1, "maximum": 60, "multiple": 5},
	{"group": "lunge", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 60, "name": "Dumbbell Lunge (per leg)", "grp": 1, "maximum": 40, "multiple": 2},
	{"group": "twists", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 55, "name": "Kettle Bell Twists", "grp": 1, "maximum": 100, "multiple": 2},
	{"group": "spress", "bumper": false, "weight": .25, "not-reps": false, "maxweight": 55, "name": "Kettle Bell Clean/Press (per arm)", "grp": 1, "maximum": 40, "multiple": 5},
	{"group": "ghr", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "GHR Sit-up", "grp": 1, "maximum": 50, "multiple": 2},
	{"group": "pressup", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 0, "name": "Alternating-hand Ball Press-up", "grp": 1, "maximum": 40, "multiple": 2},
	{"group": "grip", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 185, "name": "Spiders", "grp": 1, "maximum": 100, "multiple": 5},
	{"group": "clean", "bumper": true, "weight": 1, "not-reps": false, "maxweight": 225, "name": "Cleans", "grp": 1, "maximum": 40, "multiple": 2},
	{"group": "snatch", "bumper": true, "weight": 1, "not-reps": false, "maxweight": 185, "name": "Snatches", "grp": 1, "maximum": 40, "multiple": 2},
	{"group": "clean", "bumper": true, "weight": 1, "not-reps": false, "maxweight": 225, "name": "Clean and Jerk", "grp": 1, "maximum": 40, "multiple": 2},
	{"group": "oblique", "bumper": false, "weight": 1, "not-reps": false, "maxweight": 55, "name": "Dumbell side raise (per side)", "grp": 1, "maximum": 40, "multiple": 2}
];
cf.workouts=[
	{"calc-reps": true, "name": "3 Rounds for time", "repmod": [.2, .2, .3, .2, .2], "lbsmod": [1, 1, 1, 1, 1], "mod": 0, "round": true},
	{"calc-reps": true, "name": "3 Rounds for time", "repmod": [.2, .4, .3, .2], "lbsmod": [1, 1, 1, 1], "mod": 0, "round": true},
	{"calc-reps": true, "name": "3 Rounds for time", "repmod": [.4, .3, .4], "lbsmod": [1, 1, 1], "mod": 0, "round": true},
	{"calc-reps": false, "name": "Triangulate (1-3-6-10-15)", "repmod": [0, 0], "lbsmod": [1, 1], "mod": 1, "round": true},
	{"calc-reps": true, "name": "Exercises for time", "repmod": [.6, .4, .8, .4, .6], "lbsmod": [1, 1, 1, 1, 1], "mod": 1, "round": true},
	{"calc-reps": false, "name": "10-9-8-7-6-5-4-3-2-1", "repmod": [0, 0], "lbsmod": [1, 1], "mod": 1, "round": true},
	{"calc-reps": false, "name": "10-9-8-7-6-5-4-3-2-1", "repmod": [0, 0, 0], "lbsmod": [1, 1, 1], "mod": 1, "round": true},
	{"calc-reps": true, "name": "5 Rounds for time", "repmod": [.1, .3, .2], "lbsmod": [1, 1, 1], "mod": 1, "round": true},
	{"calc-reps": false, "name": "21-15-9", "repmod": [0, 0], "lbsmod": [1, 1], "mod": 1, "round": true},
	{"calc-reps": false, "name": "21-15-9", "repmod": [0, 0, 0], "lbsmod": [1, 1, 1], "mod": 1, "round": true},
	{"calc-reps": false, "name": "Cubication (1-8-27)", "repmod": [0, 0, 0], "lbsmod": [1, 1, 1], "mod": 1, "round": true},
	{"calc-reps": true, "name": "10 Rounds", "repmod": [.08, .12], "mod": 0, "lbsmod": [1, 1], "round": true},
	{"calc-reps": true, "name": "10 Rounds", "repmod": [.06, .08, .06], "mod": 0, "lbsmod": [1, 1, 1], "round": true},
	{"calc-reps": true, "name": "On the 30s for 30 mins", "repmod": [.05, .08, .06], "lbsmod": [1, 1, 1], "mod": 0, "round": false},
	{"calc-reps": true, "name": "On the 30s for 30 mins", "repmod": [.07, .13], "lbsmod": [1, 1], "mod": 0, "round": false},
	{"calc-reps": false, "name": "Fibonacci (1-1-2-3-5-8-13)", "repmod": [0, 0, 0, 0], "lbsmod": [1, 1, 1, 1], "mod": 1, "round": true},
	{"calc-reps": false, "name": "Fibonacci (1-1-2-3-5-8-13)", "repmod": [0, 0, 0], "lbsmod": [1, 1, 1], "mod": 1, "round": true},
	{"calc-reps": true, "name": "Max rounds in 20 minutes", "repmod": [.05, .08, .06], "lbsmod": [1, 1, 1], "mod": 0, "round": false},
	{"calc-reps": true, "name": "The 4 X 4 (four rounds of four)", "repmod": [.3, .2, .4, .2], "lbsmod": [1, 1, 1, 1], "mod": 1, "round": true},
	{"calc-reps": true, "name": "Pyramid (for time)", "repmod": [.1, .3, .6, .8, .6, .3, .1], "lbsmod": [1, 1, 1, 1, 1, 1, 1], "mod": 1, "round": true},
	{"calc-reps": true, "name": "Mach 2 (for time)", "repmod": [1, 1], "lbsmod": [1, 1], "mod": 1, "round": true},
	{"calc-reps": true, "name": "Mach 3 (for time)", "repmod": [1, 1, 1], "lbsmod": [1, 1, 1], "mod": 1, "round": true},
	{"calc-reps": true, "name": "Death by Doubling", "repmod": [2], "lbsmod": [1], "mod": 1, "round": true}			
];
